In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

We will perform Chi Square Test to understand if there a significant change in the categorical outcomes such as Signing Up, Downloading, Filling Submission Form and Purchase with CTA Button and Color Schema change.

Null Hypothesis (H0): There is no significant difference in the proportions of SignUp, Download, Form Submission and Purchase among the groups.
Alternative Hypothesis (H1): There is a significant difference in the proportions of SignUp, Download, Form Submission and Purchase among the groups.

In [10]:
data = pd.read_csv('/Users/busebahadir/Desktop/A:B Testing/digital_marketing_dataset.csv')

In [11]:
#Let's create the contingency tables
crossed_1 = pd.crosstab(data.Group, data.SignUps)
crossed_2 = pd.crosstab(data.Group, data.Downloads)
crossed_3 = pd.crosstab(data.Group, data.FormSubmissions)
crossed_4 = pd.crosstab(data.Group, data.Purchases)

In [4]:
import scipy as sp
import scipy.stats

In [5]:
x2, p, dof, expected = sp.stats.chi2_contingency(crossed_1,correction=False)

In [6]:
print("Chi-square: %(x2)s" %locals() )
print("p-value: %(p)s" %locals() )
print("Degree of freedom: %(dof)s" %locals() )
print(expected)

if p < 0.01:
    print("Significant at 1% level of significance")
elif p < 0.05:
    print("Significant at 5% level of significance")
else:
    print("Not significant at 5% level of significance")

Chi-square: 0.6317332232713673
p-value: 0.426720268137768
Degree of freedom: 1
[[1046.  454.]
 [1046.  454.]]
Not significant at 5% level of significance


In [7]:
x2, p, dof, expected = sp.stats.chi2_contingency(crossed_2,correction=False)
print("Chi-square: %(x2)s" %locals() )
print("p-value: %(p)s" %locals() )
print("Degree of freedom: %(dof)s" %locals() )
print(expected)

if p < 0.01:
    print("Significant at 1% level of significance")
elif p < 0.05:
    print("Significant at 5% level of significance")
else:
    print("Not significant at 5% level of significance")

Chi-square: 1.9750917838785105
p-value: 0.15990843345248562
Degree of freedom: 1
[[1194.5  305.5]
 [1194.5  305.5]]
Not significant at 5% level of significance


In [8]:
x2, p, dof, expected = sp.stats.chi2_contingency(crossed_3,correction=False)
print("Chi-square: %(x2)s" %locals() )
print("p-value: %(p)s" %locals() )
print("Degree of freedom: %(dof)s" %locals() )
print(expected)

if p < 0.01:
    print("Significant at 1% level of significance")
elif p < 0.05:
    print("Significant at 5% level of significance")
else:
    print("Not significant at 5% level of significance")

Chi-square: 0.7383074569053147
p-value: 0.39020360000825294
Degree of freedom: 1
[[908.5 591.5]
 [908.5 591.5]]
Not significant at 5% level of significance


In [9]:
x2, p, dof, expected = sp.stats.chi2_contingency(crossed_4,correction=False)
print("Chi-square: %(x2)s" %locals() )
print("p-value: %(p)s" %locals() )
print("Degree of freedom: %(dof)s" %locals() )
print(expected)

if p < 0.01:
    print("Significant at 1% level of significance")
elif p < 0.05:
    print("Significant at 5% level of significance")
else:
    print("Not significant at 5% level of significance")

Chi-square: 0.1757786576011116
p-value: 0.6750263791467721
Degree of freedom: 1
[[1344.5  155.5]
 [1344.5  155.5]]
Not significant at 5% level of significance


None of the turnover outcomes produces significant differences among Control and Test groups. Therefore, according to Chi-Square test, there is no evidence to decide whether we should select Button A or B, and Color Schema 1 or 2, based on the results of this A/B testing dataset.